### ISSUE TITLE
No such var: clojure.core.cache/through (plus workaround)

### ISSUE THREAD

**Issue by telent** [semperos/clj-webdriver#132]
Adding [clj-wedriver "0.6.1"] to my project using clojure 0.6 caused errors whenever I ran `lein test`: 

```
:; lein test
Compiling ClojureScript.
Exception in thread "main" java.lang.RuntimeException: No such var: clojure.core.cache/through, compiling:(clojure/core/memoize.clj:52:3)
```

Guessing that the `[org.clojure/core.cache "0.5.0"]` in clj-webdriver's project.clj was too old a version for some other dependency I am pulling in (possible suspects include clojure, clojurescript, core.async - my full project.clj is at https://github.com/telent/sledge/blob/master/project.clj) I added an explicit `[org.clojure/core.cache "0.6.4"]` in my  project and it now seems happy.  You might want to update the README to mention this, unless of course a new release is imminent.

**Comment by limist** [comment]
Ran into this as well; hope to see a new stable release soon of `clj-webdriver`

**Comment by semperos** [comment]
The evolution of dependencies is wonderful, but something that, if folks need to utilize a later version of a certain transitive dependency that this library uses, a PR would be welcome that brings the particular dependency up-to-date and changes this project's code accordingly (though it sounds like it might not even need any changes outside updating the `project.clj`, since you were able to use a later version of the library).
